//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "Widget1.xaml.h"

void ::Cheat::Widget1::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///Widget1.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::Cheat::Widget1::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->canvasSwapChainPanel = safe_cast<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasSwapChainPanel^>(__target);
            (safe_cast<::Microsoft::Graphics::Canvas::UI::Xaml::CanvasSwapChainPanel^>(this->canvasSwapChainPanel))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Cheat::Widget1::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Widget1::canvasSwapChainPanel_Loaded);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Cheat::Widget1::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


